services:
  - type: web
    name: anaylytics
    env: docker
    repo: https://github.com/ashabhussan/umami.git
    region: oregon # optional (defaults to oregon)
    plan: free
    branch: main
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: anaylytics-db
          property: connectionString
      - key: HASH_SALT
        generateValue: true

databases:
  - name: anaylytics-db
    plan: free
    databaseName: anaylytics-db
    user: umami
